import { ServiceDetail, PortfolioItem, Testimonial } from "./types";

export const SERVICES: ServiceDetail[] = [
  {
    id: "branding",
    titleEn: "Logo & Branding",
    titleBn: "লোগো এবং ব্র্যান্ডিং",
    descEn: "We craft distinctive brand visual identities and corporate guidelines that make a lasting impression and ensure long-term business alignment.",
    descBn: "আমরা ওয়ান অফ এ কাইন্ড ব্র্যান্ড ভিজ্যুয়াল আইডেন্টিটি এবং কর্পোরেট গাইডলাইন তৈরি করি যা দীর্ঘমেয়াদী ব্যবসায়িক প্রবৃদ্ধি নিশ্চিত করে।",
    icon: "Palette",
    subservices: [
      "Custom Logo Design",
      "Branding Consultancy",
      "Brand Guidelines Booklet",
      "Corporate Identity Kit"
    ]
  },
  {
    id: "web-dev",
    titleEn: "Web Development",
    titleBn: "ওয়েব ডেভেলপমেন্ট",
    descEn: "Engineered for speed, high-conversion rates, and SEO performance. Offering landing pages, web applications, and premium e-commerce solutions.",
    descBn: "গতি, হাই কনভার্শন রেট এবং এসইও এর জন্য বিশেষভাবে অপ্টিমাইজড। আকর্ষণীয় ল্যান্ডিং পেজ, ওয়েব পোর্টফোলিও এবং প্রিমিয়াম ই-কমার্স সমাধান।",
    icon: "Layout",
    subservices: [
      "Website Design & Dev",
      "Landing Page Creation",
      "Corporate Web Portfolios",
      "Full-featured E-commerce Platform"
    ]
  },
  {
    id: "marketing",
    titleEn: "Digital Marketing",
    titleBn: "ডিজিটাল মার্কেটিং",
    descEn: "Data-driven advertising campaigns built for ROI. Maximize your digital advertising reach across Facebook, Google, and LinkedIn channels.",
    descBn: "উচ্চ রিটার্ন অন ইনভেস্টমেন্ট (ROI) ভিত্তিক ডেটা-চালিত বিজ্ঞাপন ক্যাম্পেইন। ফেসবুক, গুগল এবং লিঙ্কডইন চ্যানেলে সর্বোচ্চ রিচ নিশ্চিত করুন।",
    icon: "TrendingUp",
    subservices: [
      "Facebook Ad Campaigns",
      "Google Search & Display Ads",
      "LinkedIn Leads Generation",
      "Advanced Search Engine Optimization (SEO)"
    ]
  },
  {
    id: "ai-video",
    titleEn: "AI Video Production",
    titleBn: "এআই ভিডিও প্রডাকশন",
    descEn: "Scale your content production speed with AI-assisted video editing, professional corporate showreels, and full YouTube channel optimization.",
    descBn: "এআই-অ্যাসিস্টেড ভিডিও এডিটিং, আকর্ষণীয় কর্পোরেট শোরিল এবং সম্পূর্ণ ইউটিউব চ্যানেল অপ্টিমাইজেশনের মাধ্যমে কনটেন্ট প্রোডাকশন দ্রুত করুন।",
    icon: "Video",
    subservices: [
      "AI Content Creator Videos",
      "AI Corporate Showreels",
      "YouTube Automation Setups",
      "Video SEO & Growth Strategies"
    ]
  }
];

export const PORTFOLIO: PortfolioItem[] = [
  {
    id: "p1",
    titleEn: "Premium E-commerce Architecture",
    titleBn: "প্রিমিয়াম ই-কমার্স আর্কিটেকচার",
    category: "web",
    categoryLabelEn: "Web Dev",
    categoryLabelBn: "ওয়েব ডেভ",
    image: "https://ezydigitalhub.com/wp-content/uploads/2026/04/Website.webp",
    stats: "320% Checkout ROI Growth"
  },
  {
    id: "p2",
    titleEn: "Comprehensive Corporate Brand Identity",
    titleBn: "সম্পূর্ণ কর্পোরেট ব্র্যান্ড আইডেন্টিটি",
    category: "branding",
    categoryLabelEn: "Branding",
    categoryLabelBn: "ব্র্যান্ডিং",
    image: "https://ezydigitalhub.com/wp-content/uploads/2026/04/Branding-logo-post.webp",
    stats: "Consistent Visual Alignment"
  },
  {
    id: "p3",
    titleEn: "Data-Driven Scaling Campaign",
    titleBn: "ডেটা-চালিত ব্যবসায়িক প্রবৃদ্ধি ক্যাম্পেইন",
    category: "marketing",
    categoryLabelEn: "Marketing",
    categoryLabelBn: "মার্কেটিং",
    image: "https://ezydigitalhub.com/wp-content/uploads/2026/04/Business-growth.webp",
    stats: "15x Return on Ad Spend (ROAS)"
  },
  {
    id: "p4",
    titleEn: "High-Performance Active Workplace Video",
    titleBn: "হাই-পারফরম্যান্স কাজের পরিবেশ ল্যান্ডিং ভিডিও",
    category: "video",
    categoryLabelEn: "AI Video",
    categoryLabelBn: "এআই ভিডিও",
    image: "https://ezydigitalhub.com/wp-content/uploads/2026/04/DSC_2784.webp",
    stats: "2.4M Accumulated Views"
  },
  {
    id: "p5",
    titleEn: "Strategic Product Launch Visuals",
    titleBn: "কৌশলগত পণ্য লঞ্চের ভিজ্যুয়াল প্রজেক্ট",
    category: "branding",
    categoryLabelEn: "Branding",
    categoryLabelBn: "ব্র্যান্ডিং",
    image: "https://ezydigitalhub.com/wp-content/uploads/2026/04/DSC_2802.webp",
    stats: "High Conversion Rate Focus"
  }
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "t1",
    name: "Mohammad Rahman",
    roleEn: "Managing Director",
    roleBn: "ব্যবস্থাপনা পরিচালক",
    company: "Apex Tech Bangladesh",
    contentEn: "Ezy Digital Hub completely overhauled our digital footprint. Our website loading seed dropped below 1 second, and the incoming leads from Google SEO quadrupled within 3 months!",
    contentBn: "ইজি ডিজিটাল হাব আমাদের ডিজিটাল ফুটপ্রিন্টকে পুরোপুরি বদলে দিয়েছে। আমাদের ওয়েবসাইটের স্পিড ১ সেকেন্ডের নিচে নেমে এসেছে এবং গুগল এসইও থেকে লিডস ৩ মাসে প্রায় ৪ গুণ বেড়েছে!",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200"
  },
  {
    id: "t2",
    name: "Sadia Chowdhury",
    roleEn: "Head of Marketing",
    roleBn: "মার্কেটিং প্রধান",
    company: "Elegance Fashion House",
    contentEn: "Their Facebook ad campaigns scaled our sales to absolute heights. Ezy Digital Hub understands the local demographic and targets precisely, yielding incredible ROI.",
    contentBn: "তাদের ফেসবুক অ্যাড ক্যাম্পেইন আমাদের সেলসকে কল্পনাতীত উচ্চতায় নিয়ে গেছে। ইজি ডিজিটাল হাব স্থানীয় কাস্টমারদের মনস্তত্ত্ব বোঝে এবং নিখুঁতভাবে টার্গেট করতে পারে।",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200"
  },
  {
    id: "t3",
    name: "Tanvir Hasan",
    roleEn: "Co-Founder",
    roleBn: "সহ-প্রতিষ্ঠাতা",
    company: "Shwapno Real Estate Solutions",
    contentEn: "Working with them for our corporate brand revamp and landing page web development was flawless. The slide animations, mobile responsiveness, and design style are unmatched.",
    contentBn: "কর্পোরেট ব্র্যান্ড রিভ্যাম্প এবং ল্যান্ডিং পেজ ডেভেলপমেন্টের কাজের জন্য তাদের সাথে পথচলা দারুণ ছিল। স্লাইড অ্যানিমেশন ও মোবাইল ডিজাইন সত্যিই সেরা মানের ছিল।",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200"
  }
];

export const DICTIONARY = {
  en: {
    meetingBtn: "Book a Meeting",
    meetingDesc: "Schedule a free 15-minute consultation calendar slot with Ezy Digital Hub specialized architects.",
    ourStory: "Our Story",
    ourTeam: "Our Team",
    branding: "Logo & Branding",
    logoDesign: "Logo Design",
    brandingConsultancy: "Branding Consultancy",
    businessAlignment: "Business Alignment",
    webDev: "Web Development",
    webDesignDev: "Website Design & Dev",
    landingPage: "Landing Page Design",
    businessPortfolio: "Business Portfolio",
    ecommerce: "Ecommerce Website",
    marketing: "Digital Marketing",
    fbCamp: "FB Ad Camp",
    googleCamp: "Google Ad Camp",
    linkedinCamp: "LinkedIn Ad Camp",
    seoService: "SEO Service",
    aiVideo: "AI Video",
    aiContent: "AI Content Video",
    aiCorp: "AI Corporate Video",
    ytOpt: "YouTube Optimization",
    ytSeo: "YouTube SEO",
    portfolio: "Portfolio",
    clientsLove: "Clients Love",
    contact: "Contact",
    home: "Home",
    about: "About",
    services: "Services",
    tagline: "Empowering Your Digital Presence",
    heroDesc: "Ezy Digital Hub is a premium digital agency dedicated to transforming brand visual identities, building lightning-fast custom web solutions, and executing data-driven ROI growth marketing plans.",
    exploreWorks: "Explore Works",
    ourServices: "Our Services",
    happyClients: "Happy Clients",
    coreConcept: "Our Core Concept",
    elevatingBrands: "Elevating Brands with Scalable Digital Strategy",
    bdBeyond: "Delivering High-Performance Solutions Across Bangladesh & Beyond.",
    aboutText: "At Ezy Digital Hub, we believe technology should be an accelerator, not a barrier. We combine technical engineering with creative marketing to build secure, conversion-driven assets that fuel long-term business growth.",
    statsSub: "Trusted by visionary leaders to deliver stunning results",
    projectsDelivered: "Projects Completed",
    retentionRate: "Client Retention",
    yearsOfExp: "Years of Experience",
    innovativeSols: "What We Specialize In",
    exploreGrid: "Custom Visuals and Conversion Funnels Engineered For Any Device",
    portfolioTitle: "Our Work Showcase",
    portfolioDesc: "See how Ezy Digital Hub delivers tangible ROI and stunning design alignment for businesses.",
    catAll: "All Projects",
    catWeb: "Web Architecture",
    catBranding: "Brand Identity",
    catMarketing: "Performance Ads",
    catVideo: "AI Video & SEO",
    clientsLoveTitle: "What Visionary Leaders Say",
    clientsLoveSub: "Hear directly from our verified clients across diverse business sectors about the tangible impact we delivered.",
    contactTitle: "Get in Touch With Us",
    contactSub: "Ready to scale your digital presence? Send a quick message or request an instant WhatsApp consultation.",
    placeholderName: "Your Full Name",
    placeholderEmail: "Your Email Address",
    placeholderPhone: "Your Phone Number (optional)",
    placeholderMessage: "Describe your project scale and scope...",
    sendMessage: "Send Project Inquiry",
    sending: "Sending Inquiry...",
    sentSuccess: "Your message was sent successfully! We'll reply within 2 hours.",
    addressTitle: "Our Headquarters",
    addressDesc: "Baridhara DOHS, Dhaka, Bangladesh",
    hoursTitle: "Work Duration Hours",
    hoursDesc: "Sunday - Thursday: 9:00 AM - 6:00 PM (GMT+6)",
    whatsappBtn: "WHATSAPP CONSULTATION",
    empoweringGrowth: "Empowering Digital Growth",
    descriptionText: "A premium digital agency specializing in high-performance web architecture and data-driven marketing.",
    allRightsReserved: "ALL RIGHTS RESERVED.",
    privacyPolicy: "PRIVACY POLICY",
    terms: "TERMS"
  },
  bn: {
    meetingBtn: "মিটিং বুক করুন",
    meetingDesc: "ইজি ডিজিটাল হাব বিশেষজ্ঞদের সাথে একটি ফ্রি ১৫-মিনিটের পরামর্শ মিটিং শিডিউল করুন।",
    ourStory: "আমাদের গল্প",
    ourTeam: "আমাদের টিম",
    branding: "লোগো এবং ব্র্যান্ডিং",
    logoDesign: "লোগো ডিজাইন",
    brandingConsultancy: "ব্র্যান্ডিং পরামর্শ",
    businessAlignment: "ব্যবসায়িক সামঞ্জস্য",
    webDev: "ওয়েব ডেভেলপমেন্ট",
    webDesignDev: "ওয়েবসাইট ডিজাইন ও ডেভ",
    landingPage: "ল্যান্ডিং পেজ ডিজাইন",
    businessPortfolio: "বিজনেস পোর্টফোলিও",
    ecommerce: "ই-কমার্স ওয়েবসাইট",
    marketing: "ডিজিটাল মার্কেটিং",
    fbCamp: "ফেসবুক অ্যাড ক্যাম্পেইন",
    googleCamp: "গুগল অ্যাড ক্যাম্পেইন",
    linkedinCamp: "লিঙ্কডইন ক্যাম্পেইন",
    seoService: "এসইও সার্ভিস",
    aiVideo: "এআই ভিডিও",
    aiContent: "এআই কনটেন্ট ভিডিও",
    aiCorp: "এআই কর্পোরেট ভিডিও",
    ytOpt: "ইউটিউব অপ্টিমাইজেশন",
    ytSeo: "ইউটিউব এসইও",
    portfolio: "পোর্টফোলিও",
    clientsLove: "ক্লায়েন্ট মতামত",
    contact: "যোগাযোগ",
    home: "হোম",
    about: "আমাদের সম্পর্কে",
    services: "সেবাসমূহ",
    tagline: "আপনার ডিজিটাল উপস্থিতি শক্তিশালী করা",
    heroDesc: "ইজি ডিজিটাল হাব হলো একটি প্রিমিয়াম ডিজিটাল এজেন্সি যা ব্রান্ডের ভিজ্যুয়াল আইডেন্টিটি রূপান্তর করতে, বিদ্যুৎ-গতির কাস্টম ওয়েব সলিউশন তৈরি করতে এবং ডেটা-চালিত গ্রোথ মার্কেটিং ক্যাম্পেইন চালাতে একনিষ্ঠভাবে কাজ করে।",
    exploreWorks: "কাজগুলো দেখুন",
    ourServices: "আমাদের সেবাসমূহ",
    happyClients: "সন্তুষ্ট কাস্টমার",
    coreConcept: "আমাদের মূল দর্শন",
    elevatingBrands: "স্কেলযোগ্য ডিজিটাল কৌশলের মাধ্যমে ব্রান্ডের উন্নয়ন",
    bdBeyond: "বাংলাদেশ ও বিশ্বজুড়ে উচ্চ-মানের আধুনিক প্রযুক্তি ও সমাধান সরবরাহ করছি।",
    aboutText: "ইজি ডিজিটাল হাব-এ আমরা বিশ্বাস করি প্রযুক্তি হওয়া উচিত ব্যবসার গতি বৃদ্ধির মাধ্যম। সুরক্ষিত ও কনভার্শন-ভিত্তিক পণ্য তৈরি করার জন্য আমরা জটিল ইঞ্জিনিয়ারিংয়ের সাথে শৈল্পিক মার্কেটিং যুক্ত করি যা ব্যবসার দীর্ঘমেয়াদী উন্নতি সাধনে সাহায্য করে।",
    statsSub: "বিশ্বাসযোগ্য ফলাফলের মাধ্যমে ব্যবসায়িক লক্ষ্যের সর্বোচ্চ অর্জন",
    projectsDelivered: "সমাপ্ত প্রজেক্ট",
    retentionRate: "ক্লায়েন্ট রিটেনশন",
    yearsOfExp: "অভিজ্ঞতার বছর",
    innovativeSols: "আমাদের বিশেষ সেবাসমূহ",
    exploreGrid: "যেকোনো ডিভাইসের জন্য উচ্চমানের কাস্টম ভিজ্যুয়াল এবং কনভার্শন ফানেল",
    portfolioTitle: "আমাদের কাজের গ্যালারি",
    portfolioDesc: "ইজি ডিজিটাল হাব কিভাবে আপনার ব্যবসার আয় বাড়াতে ও রূপ দান করতে সক্ষম তা স্বচক্ষে দেখুন।",
    catAll: "সব প্রজেক্ট",
    catWeb: "ওয়েব আর্কিটেকচার",
    catBranding: "ব্র্যান্ড আইডেন্টিটি",
    catMarketing: "পারফরম্যান্স অ্যাডস",
    catVideo: "এআই ভিডিও ও এসইও",
    clientsLoveTitle: "নেতৃস্থানীয় উদ্যোক্তাদের জবানবন্দী",
    clientsLoveSub: "আমাদের কাজ দ্বারা ব্যবসার বৃদ্ধি হওয়া সন্তুষ্ট ক্লায়েন্টদের কাছ থেকে সরাসরি শুনুন তাদের ডিজিটাল পরিবর্তনের বাস্তব গল্প।",
    contactTitle: "যোগাযোগের সেরা মাধ্যম",
    contactSub: "আপনার ব্র্যান্ড নিয়ে কাজ করতে তৈরি? আজই আমাদের সাথে মেসেজে যোগাযোগ করুন অথবা সরাসরি হোয়াটসঅ্যাপে বার্তা দিন।",
    placeholderName: "আপনার পুরো নাম",
    placeholderEmail: "আপনার ইমেল অ্যাড্রেস",
    placeholderPhone: "আপনার ফোন নম্বর (ঐচ্ছিক)",
    placeholderMessage: "প্রজেক্টের কাজের বিবরণ বিস্তারিত লিখুন...",
    sendMessage: "ইনকোয়ারি পাঠান",
    sending: "মেসেজ পাঠানো হচ্ছে...",
    sentSuccess: "আপনার মেসেজ সফলভাবে পাঠানো হয়েছে! আগামী ২ ঘন্টার মধ্যে আমরা যোগাযোগ করব।",
    addressTitle: "আমাদের সদর দপ্তর",
    addressDesc: "বারিধারা ডিওএইচএস, ঢাকা, বাংলাদেশ",
    hoursTitle: "কাজের সময়সূচী",
    hoursDesc: "রবিবার - বৃহস্পতিবার: সকাল ৯:০০ - সন্ধ্যা ৬:০০টা (GMT+6)",
    whatsappBtn: "হোয়াটসঅ্যাপ কনসালটেশন",
    empoweringGrowth: "ডিজিটাল গ্রোথের ক্ষমতায়ন",
    descriptionText: "উচ্চ-মানের কাস্টম ওয়েব সলিউশন এবং রিটার্ন-ভিত্তিক ডিজিটাল মার্কেটিংয়ের জন্য প্রিমিয়াম ডিজাইন ও টেক এজেন্সি।",
    allRightsReserved: "সর্বস্বত্ব সংরক্ষিত।",
    privacyPolicy: "প্রাইভেসি পলিসি",
    terms: "শর্তাবলী"
  }
};
